/*
 * countmatic api
 * countmatic is a service to provide counters as web service. Sure, counters are simple artefacts of IT systems. But they are part of *every* system. There are numerous use cases where you need distributed enumerators in IoT manufacturing or i.e. production reporting.    Find out more [https://countmatic.io](https://countmatic.io).
 *
 * OpenAPI spec version: 2.0.2
 * Contact: countmaster@countmatic.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.countmatic.api_v2.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * a single counter with name, reading and modification timestamp
 */
@ApiModel(description = "a single counter with name, reading and modification timestamp")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-02-12T17:36:10.819Z")
public class Counter {
  @SerializedName("name")
  private String name = null;

  @SerializedName("count")
  private Long count = null;

  @SerializedName("modified")
  private Long modified = null;

  public Counter name(String name) {
    this.name = name;
    return this;
  }

   /**
   * the name of this counter
   * @return name
  **/
  @ApiModelProperty(value = "the name of this counter")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Counter count(Long count) {
    this.count = count;
    return this;
  }

   /**
   * the current reading
   * @return count
  **/
  @ApiModelProperty(value = "the current reading")
  public Long getCount() {
    return count;
  }

  public void setCount(Long count) {
    this.count = count;
  }

  public Counter modified(Long modified) {
    this.modified = modified;
    return this;
  }

   /**
   * the last write access as unix UTC timestamp
   * @return modified
  **/
  @ApiModelProperty(value = "the last write access as unix UTC timestamp")
  public Long getModified() {
    return modified;
  }

  public void setModified(Long modified) {
    this.modified = modified;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Counter counter = (Counter) o;
    return Objects.equals(this.name, counter.name) &&
        Objects.equals(this.count, counter.count) &&
        Objects.equals(this.modified, counter.modified);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, count, modified);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Counter {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    count: ").append(toIndentedString(count)).append("\n");
    sb.append("    modified: ").append(toIndentedString(modified)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

