/*
 * countmatic api
 * countmatic is a service to provide counters as web service. Sure, counters are simple artefacts of IT systems. But they are part of *every* system. There are numerous use cases where you need distributed enumerators in IoT manufacturing or i.e. production reporting.    Find out more [https://countmatic.io](https://countmatic.io).
 *
 * OpenAPI spec version: 2.0.2
 * Contact: countmaster@countmatic.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.countmatic.api.v2;

import io.countmatic.api.v2.ApiException;
import io.countmatic.api.v2.model.Counter;
import io.countmatic.api.v2.model.Error;
import io.countmatic.api.v2.model.ServerInfo;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for StatsApi
 */
@Ignore
public class StatsApiTest {

    private final StatsApi api = new StatsApi();

    
    /**
     * Request the number of currently open counters on that countmatic backend
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getNumberOfCountersTest() throws ApiException {
        Counter response = api.getNumberOfCounters();

        // TODO: test validations
    }
    
    /**
     * Request information about the cm backend and its load
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getServerInfoTest() throws ApiException {
        ServerInfo response = api.getServerInfo();

        // TODO: test validations
    }
    
}
